# Generated by Django 4.1.1 on 2024-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('stay', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=80)),
                ('response', models.TextField()),
                ('videoId_1', models.CharField(max_length=80)),
                ('url_1', models.CharField(max_length=80)),
                ('title_1', models.CharField(max_length=80)),
                ('thumbnails_1', models.CharField(max_length=80)),
                ('videoId_2', models.CharField(max_length=80)),
                ('url_2', models.CharField(max_length=80)),
                ('title_2', models.CharField(max_length=80)),
                ('thumbnails_2', models.CharField(max_length=80)),
                ('videoId_3', models.CharField(max_length=80)),
                ('url_3', models.CharField(max_length=80)),
                ('title_3', models.CharField(max_length=80)),
                ('thumbnails_3', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
